# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e9d8a1ddfc4e6fca9748ed2910fbf8b5b8fe7efb5a3ed1e6973748b7d983e0aa3f291c02076d28caf321cc4ee93114452f050c8fe82e903893d3f658f7b517

test:
  secret_key_base: 55e8a31803e81d32e2dcc6ca5fd7e9bc3f80009e31bcd615a952e48cb2579b56d8d502725f7fd5f903b652ff4e38e01cdf2d9dd32ae2816e2b10efa5c4b6be89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
